<?php /** @var Speroteck\Task2\Block\Posts $block */ ?>
    <h1>Toptal Posts</h1>
<?php foreach($block->getPosts() as $post): ?>
    <?php /** @var Speroteck\Task2\Model\Post */ ?>
    <h2><a href="<?php echo $block->getPostUrl($post);?>"><?php echo $post->getTitle(); ?></a></h2>
    <p><?php echo $post->getContent(); ?></p>
<?php endforeach; ?>

    <h2><a href="<?php echo $block->getDelPostUrl();?>"><?php echo "Clear data"; ?></a></h2>
    <h2><a href="<?php echo $block->getAddPostUrl();?>"><?php echo "Add data"; ?></a></h2>
